//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaType as $Schema } from "./schema";
import type { FindManyArgs as $FindManyArgs, FindUniqueArgs as $FindUniqueArgs, FindFirstArgs as $FindFirstArgs, CreateArgs as $CreateArgs, CreateManyArgs as $CreateManyArgs, CreateManyAndReturnArgs as $CreateManyAndReturnArgs, UpdateArgs as $UpdateArgs, UpdateManyArgs as $UpdateManyArgs, UpdateManyAndReturnArgs as $UpdateManyAndReturnArgs, UpsertArgs as $UpsertArgs, DeleteArgs as $DeleteArgs, DeleteManyArgs as $DeleteManyArgs, CountArgs as $CountArgs, AggregateArgs as $AggregateArgs, GroupByArgs as $GroupByArgs, WhereInput as $WhereInput, SelectInput as $SelectInput, IncludeInput as $IncludeInput, OmitInput as $OmitInput, QueryOptions as $QueryOptions } from "@zenstackhq/orm";
import type { SimplifiedPlainResult as $Result, SelectIncludeOmit as $SelectIncludeOmit } from "@zenstackhq/orm";
export type PostFindManyArgs = $FindManyArgs<$Schema, "Post">;
export type PostFindUniqueArgs = $FindUniqueArgs<$Schema, "Post">;
export type PostFindFirstArgs = $FindFirstArgs<$Schema, "Post">;
export type PostCreateArgs = $CreateArgs<$Schema, "Post">;
export type PostCreateManyArgs = $CreateManyArgs<$Schema, "Post">;
export type PostCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, "Post">;
export type PostUpdateArgs = $UpdateArgs<$Schema, "Post">;
export type PostUpdateManyArgs = $UpdateManyArgs<$Schema, "Post">;
export type PostUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, "Post">;
export type PostUpsertArgs = $UpsertArgs<$Schema, "Post">;
export type PostDeleteArgs = $DeleteArgs<$Schema, "Post">;
export type PostDeleteManyArgs = $DeleteManyArgs<$Schema, "Post">;
export type PostCountArgs = $CountArgs<$Schema, "Post">;
export type PostAggregateArgs = $AggregateArgs<$Schema, "Post">;
export type PostGroupByArgs = $GroupByArgs<$Schema, "Post">;
export type PostWhereInput = $WhereInput<$Schema, "Post">;
export type PostSelect = $SelectInput<$Schema, "Post">;
export type PostInclude = $IncludeInput<$Schema, "Post">;
export type PostOmit = $OmitInput<$Schema, "Post">;
export type PostGetPayload<Args extends $SelectIncludeOmit<$Schema, "Post", true>, Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>> = $Result<$Schema, "Post", Args, Options>;
